<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Find your account and log in__55r1 _1kbt</name>
   <tag></tag>
   <elementGuidId>acadebb8-f7ca-4268-a00f-55d5f5e967a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._55r1._1kbt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginform']/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ecd0df87-e3ef-48f0-8cfc-c0e8cc491333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_55r1 _1kbt</value>
      <webElementGuid>2df632e4-36a6-4185-a79b-2f0bb2e90514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginform&quot;)/div[@class=&quot;clearfix _5466 _44mg&quot;]/div[1]/div[@class=&quot;_55r1 _1kbt&quot;]</value>
      <webElementGuid>fbfebbce-40ab-4ff8-bb29-1b37269f4344</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginform']/div[2]/div/div</value>
      <webElementGuid>00f1e728-f362-4663-909f-90354d908456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find your account and log in.'])[1]/following::div[3]</value>
      <webElementGuid>98494619-76a8-4554-9fce-7952a6405e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::div[4]</value>
      <webElementGuid>f7e9f42a-6bdd-4ff7-bfbd-7a3a31284bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgotten password?'])[1]/preceding::div[5]</value>
      <webElementGuid>3846702e-c085-4a3c-9521-b5678086a335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div</value>
      <webElementGuid>acc29878-a69d-4972-beb0-0f663f3bb550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
