<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Log in to Facebook__9ay6 img</name>
   <tag></tag>
   <elementGuidId>702373bf-51c7-4688-b91f-926c3de237e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img._9ay6.img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;email_container&quot;)/div[@class=&quot;_9ay5&quot;]/img[@class=&quot;_9ay6 img&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='email_container']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9465cf04-b127-47a9-bdaa-e9f5e5e28fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9ay6 img</value>
      <webElementGuid>8321fafe-5a60-49e5-8fe3-ae8137533ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.xx.fbcdn.net/rsrc.php/v4/y2/r/O287_AcFyg4.png</value>
      <webElementGuid>4fef39b8-dc9f-4bb4-9ca5-1f555b53494d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>c1962725-e6a7-4394-818c-d52d7096f573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>c9b9af7d-18e6-4ede-8c12-f97935e1e60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_container&quot;)/div[@class=&quot;_9ay5&quot;]/img[@class=&quot;_9ay6 img&quot;]</value>
      <webElementGuid>2be83750-fe73-46c9-8ccb-0c6f5621e356</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='email_container']/div/img</value>
      <webElementGuid>fadb87c1-a734-455a-af4f-8da884c68637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://static.xx.fbcdn.net/rsrc.php/v4/y2/r/O287_AcFyg4.png')]</value>
      <webElementGuid>c6ca3fec-2cb8-4039-bd79-2fd460b688c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/img</value>
      <webElementGuid>7793957c-165f-490f-a821-d2ba0d82e7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static.xx.fbcdn.net/rsrc.php/v4/y2/r/O287_AcFyg4.png']</value>
      <webElementGuid>00ba0e80-cc54-4887-b33b-4ace5ef864d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
