<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create a Page</name>
   <tag></tag>
   <elementGuidId>b1dcabd4-7dc0-4727-9886-835c7ba7a4e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a._8esh</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Create a Page' or . = 'Create a Page')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reg_pages_msg']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4e9c450b-a5a5-4f8c-a579-dc807e081f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pages/create/?ref_type=registration_form</value>
      <webElementGuid>7c0c62ee-f35a-4a1b-b08d-1ad031ecffe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_8esh</value>
      <webElementGuid>1b80c447-cbfb-4fee-8549-45d8cc6b9bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create a Page</value>
      <webElementGuid>3c75c0e7-45ad-48da-83d2-aba95af4b666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reg_pages_msg&quot;)/a[@class=&quot;_8esh&quot;]</value>
      <webElementGuid>e1c3cdc4-0fd6-45b0-a9cc-341a2a379bcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reg_pages_msg']/a</value>
      <webElementGuid>98f957b3-3715-470d-87c1-7d6922578389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create a Page')]</value>
      <webElementGuid>7d444e88-fc98-4661-bc43-d856cf239979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create new account'])[1]/following::a[1]</value>
      <webElementGuid>7cdacd44-907c-4c4b-adba-15c868a40496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English (UK)'])[1]/preceding::a[1]</value>
      <webElementGuid>b2ea6a23-d816-482b-ada4-5d7a0440b0e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Indonesia'])[1]/preceding::a[1]</value>
      <webElementGuid>6323c1eb-cf70-48cd-9e7a-52c4f2ae20df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create a Page']/parent::*</value>
      <webElementGuid>bf54880d-adc2-4a9c-b7f1-40ca1bfc14f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pages/create/?ref_type=registration_form')]</value>
      <webElementGuid>038d9ddb-4035-4aad-906b-5c7737919471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>5eeefb7f-ce05-41d3-8899-ead49dad7c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pages/create/?ref_type=registration_form' and (text() = 'Create a Page' or . = 'Create a Page')]</value>
      <webElementGuid>c7830b15-2cf2-4738-8796-b97cf0819e51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
