<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create a Page for a celebrity, brand or_5572c3</name>
   <tag></tag>
   <elementGuidId>ef657d08-79f3-4652-b251-7f5ef83c3299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reg_pages_msg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='reg_pages_msg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3110064c-3521-480e-891a-df4f3e205b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reg_pages_msg</value>
      <webElementGuid>39c9cee3-d937-44c6-8db8-aa51267dfbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_58mk</value>
      <webElementGuid>084a2f36-052f-49a1-b2ff-97d875e8e0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create a Page for a celebrity, brand or business.</value>
      <webElementGuid>b0a9e197-0785-49ab-9e4a-3e9afb423ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reg_pages_msg&quot;)</value>
      <webElementGuid>2235308a-5e86-4eb9-b1c4-f1f27cb5d3db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='reg_pages_msg']</value>
      <webElementGuid>7790045e-9b5d-48bb-83b7-c7c18555c237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>1b3212ec-f4ff-45ae-a08c-ab215b9a4578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create new account'])[1]/following::div[1]</value>
      <webElementGuid>1af637f7-b306-4f2f-b2c9-b8405cfaacfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgotten password?'])[1]/following::div[3]</value>
      <webElementGuid>1dc61fd2-ab67-44e5-9ac9-98b9019d7c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English (UK)'])[1]/preceding::div[1]</value>
      <webElementGuid>5b2ab52d-f8b6-4a1c-a2c7-bf068a2cb0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='for a celebrity, brand or business.']/parent::*</value>
      <webElementGuid>f340eba4-eb3f-4800-a053-8683cd19b596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>06b88b65-a180-4081-b62e-aa1b8740d1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'reg_pages_msg' and (text() = 'Create a Page for a celebrity, brand or business.' or . = 'Create a Page for a celebrity, brand or business.')]</value>
      <webElementGuid>6f8376f6-390b-400e-8a2e-c50d13ff18f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
